<a href="https://colab.research.google.com/github/pankajroy97/BCGX_Gen_AI_Virtual_Job_Internship/blob/main/Task_1_Data_Extraction_and_Initial_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
final_report=pd.read_csv("/content/Final_report.csv")
final_report.head(10)

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company
0,2023,211915,72361,411976,205753,87582,Microsoft
1,2022,198270,72738,364840,198298,89035,Microsoft
2,2021,168088,61271,333779,191791,76740,Microsoft
3,2023,96773,14974,106618,43009,13256,Tesla
4,2022,81462,12556,82338,36440,14724,Tesla
5,2021,53821,5519,62131,30548,11497,Tesla
6,2023,383285,96995,352583,290437,110543,Apple
7,2022,394328,99803,352755,302083,122151,Apple
8,2021,365817,94680,351002,287912,104038,Apple

In [ ]:
final_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Year                                 9 non-null      int64
 1   Total Revenue                        9 non-null      int64
 2   Net Income                           9 non-null      int64
 3   Total Assets                         9 non-null      int64
 4   Total Liabilities                    9 non-null      int64
 5   Cash Flow from Operating Activities  9 non-null      int64
 6   Company                              9 non-null      object
dtypes: int64(6), object(1)
memory usage: 636.0+ bytes

**Calculating Year-by-Year growth rates for Total Revenue and Net Income**

In [ ]:
final_report['Revenue_growth(%)']=final_report.groupby('Company')['Total Revenue'].pct_change()*100
final_report['Net_Income_growth(%)']=final_report.groupby('Company')['Net Income'].pct_change()*100

In [ ]:
final_report.head(10)

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue_growth(%),Net_Income_growth(%)
0,2023,211915,72361,411976,205753,87582,Microsoft,NaN,NaN
1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999
2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800
3,2023,96773,14974,106618,43009,13256,Tesla,NaN,NaN
4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990
5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919
6,2023,383285,96995,352583,290437,110543,Apple,NaN,NaN
7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995
8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112

**mputing Null/NaN values that result from pct_change calculations with 0**

In [ ]:
final_report.fillna(0,inplace=True)

In [ ]:
final_report

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue_growth(%),Net_Income_growth(%)
0,2023,211915,72361,411976,205753,87582,Microsoft,0.000000,0.000000
1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999
2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800
3,2023,96773,14974,106618,43009,13256,Tesla,0.000000,0.000000
4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990
5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919
6,2023,383285,96995,352583,290437,110543,Apple,0.000000,0.000000
7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995
8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112

**Calculating Year-by-Year growth rates for Total Assets, Total Liabilities and Cash flow from Operations Activities**

In [ ]:
final_report['Assets_growth(%)']=final_report.groupby('Company')['Total Assets'].pct_change()*100
final_report['Liabilities_growth(%)']=final_report.groupby('Company')['Total Liabilities'].pct_change()*100
final_report['cash_flow_growth(%)']=final_report.groupby('Company')['Cash Flow from Operating Activities'].pct_change()*100

In [ ]:
final_report

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue_growth(%),Net_Income_growth(%),Assets_growth(%),Liabilities_growth(%),cash_flow_growth(%)
0,2023,211915,72361,411976,205753,87582,Microsoft,0.000000,0.000000,NaN,NaN,NaN
1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,96773,14974,106618,43009,13256,Tesla,0.000000,0.000000,NaN,NaN,NaN
4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990,-22.772890,-15.273547,11.074231
5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919,-24.541524,-16.169045,-21.916599
6,2023,383285,96995,352583,290437,110543,Apple,0.000000,0.000000,NaN,NaN,NaN
7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995,0.048783,4.009820,10.500891
8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112,-0.496945,-4.691095,-14.828368

In [ ]:
final_report.fillna(0,inplace=True)

In [ ]:
final_report

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue_growth(%),Net_Income_growth(%),Assets_growth(%),Liabilities_growth(%),cash_flow_growth(%)
0,2023,211915,72361,411976,205753,87582,Microsoft,0.000000,0.000000,0.000000,0.000000,0.000000
1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,96773,14974,106618,43009,13256,Tesla,0.000000,0.000000,0.000000,0.000000,0.000000
4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990,-22.772890,-15.273547,11.074231
5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919,-24.541524,-16.169045,-21.916599
6,2023,383285,96995,352583,290437,110543,Apple,0.000000,0.000000,0.000000,0.000000,0.000000
7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995,0.048783,4.009820,10.500891
8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112,-0.496945,-4.691095,-14.828368

In [ ]:
final_report.to_csv("final_data_report.csv")

In [ ]:
summery

,Revenue_growth(%),Net_Income_growth(%),Assets_growth(%),Liabilities_growth(%),cash_flow_growth(%)
Company,,,,,
Apple,-1.449710,-0.746039,-0.149388,-0.227092,-1.442492
Microsoft,-7.220526,-5.081267,-6.651679,-2.301567,-4.050053
Tesla,-16.584240,-24.064303,-15.771471,-10.480864,-3.614123

In [ ]:
summery=final_report.groupby('Company')[['Revenue_growth(%)','Net_Income_growth(%)','Assets_growth(%)','Liabilities_growth(%)','cash_flow_growth(%)']].mean()

In [ ]:
summery.to_csv('summary_csv')